name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle wrapper
      run: ./gradlew build
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
        RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
    - name: Test with input
      uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
    - name: Clean Gradle build
      run: ./gradlew clean && rm -rf .gradle/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag example-spring-boot-helloworld:${{ steps.date.outputs.date }}
    - uses: docker/build-push-action@v2
      with:
        tags: example-spring-boot-helloworld:${{ steps.date.outputs.date }}
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: example-spring-boot-helloworld:${{ steps.date.outputs.date }}
        run: echo "hello world"
